### GET all users

GET http://localhost:3000/api/users HTTP/1.1

### GET a single user

GET http://localhost:3000/api/users/daisyd HTTP/1.1

### GET a single user which doesn't exist

GET http://localhost:3000/api/users/someNameDoesNotExist HTTP/1.1

### DELETE a user

DELETE http://localhost:3000/api/users/goofy9000 HTTP/1.1

###POST a user

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Pluto",
    "username": "plutothedog",
    "password": "pluto123"
}

### Login a user

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "minniem",
    "password": "ladymouse"
}