### GET all users

GET http://localhost:3000/api/users HTTP/1.1

### GET a single user

GET http://localhost:3000/api/users/Daisy HTTP/1.1

### GET a single user which doesn't exist

GET http://localhost:3000/api/users/sggsa HTTP/1.1

### DELETE a user

DELETE http://localhost:3000/api/users/Goofy HTTP/1.1